### PR TITLE
Make .foceiPreProcessData() work with tibbles

### PR DESCRIPTION
**Pull request by billdenney**
Related to nlmixr2/babelmixr2#52

### CODE REVIEW

**Comment by mattfidler** [comment]
The other code should be ok.  I think that things that arent purely data frames should be sanitized by this.  Including tibbles, data.tables nlmixr fit, rxode solves etc

**Comment by mattfidler** [comment]
That is the code you used that worked around the tibbles since it works for data frames too

**Comment by billdenney** [comment]
My fix in babelmixr2 will be to use as.data.frame(), but I thought while I'm at it, that making a fix for tibbles and then testing both could help.

**Comment by mattfidler** [comment]
I believe that 'rxode2' should hit CRAN soon, so I will be pushing 'nlmixr2est' right after (as I promised the CRAN maintainers)

**Pull request merged**
