### PR TITLE
Only use absolute value of the difference

### PR DESCRIPTION
**Pull request by mattfidler**

### CODE REVIEW

**Comment by billdenney** [comment]
@mattfidler I have an alternate PR in the works that also has testing built in.  Give me ~5 minutes.

**Comment by billdenney** [comment]
... the fix is functionally the same.

**Comment by mattfidler** [comment]
Oops...

**Comment by mattfidler** [comment]
Is the test the same too?

**Comment by billdenney** [comment]
The test is very similar.  I just pushed it, so you can give it a look.  My guess is that your test may be better.

**Comment by mattfidler** [comment]
Its about the same.

**Comment by billdenney** [comment]
I don't have a preference for which gets merged.  I'm just glad that I was able to make a reprex (and make a function modification to a C++ function!).

**Comment by mattfidler** [comment]
Well since you were able to do so much, I prefer to merge yours :smile:

**Pull request closed without merging**
