### PR TITLE
`est='nlme'` now has random effects

### LINKED ISSUE #103: Models estimated with `est='nlme'` do not have random effects estimated
Note that all values within the `ranef()` call at the bottom are zero.

``` r
library(nlmixr2est)
#> Loading required package: nlmixr2data

one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- log(c(0, 2.7, 100)) # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

fit_nlme <- nlmixr(one.cmt, theo_sd, est="nlme")
#> i parameter labels from comments will be replaced by 'label()'
#> > loading into symengine environment...
#> > pruning branches (`if`/`else`) of nlme model...
#> v done
#> > finding duplicate expressions in nlme model...
#> [====|====|====|====|====|====|====|====|====|====] 0:00:00
#> v done
#> 
#> **Iteration 1
#> LME step: Loglik: -229.3735, nlminb iterations: 1
#> reStruct  parameters:
#>       ID1       ID2       ID3 
#> 0.2554128 0.6019864 1.1512925 
#>  Beginning PNLS step: ..  completed fit_nlme() step.
#> PNLS step: RSS =  249.7119 
#>  fixed effects: 0.4401858  0.9615156  3.492259  
#>  iterations: 3 
#> Convergence crit. (must all become <= tolerance = 1e-05):
#>      fixed   reStruct 
#> 0.03300635 0.00000000 
#> 
#> **Iteration 2
#> LME step: Loglik: -229.3753, nlminb iterations: 1
#> reStruct  parameters:
#>       ID1       ID2       ID3 
#> 0.2554128 0.6019864 1.1512925 
#>  Beginning PNLS step: ..  completed fit_nlme() step.
#> PNLS step: RSS =  249.7119 
#>  fixed effects: 0.4401858  0.9615156  3.492259  
#>  iterations: 1 
#> Convergence crit. (must all become <= tolerance = 1e-05):
#>    fixed reStruct 
#>        0        0
#> > loading into symengine environment...
#> > pruning branches (`if`/`else`) of full model...
#> v done
#> > finding duplicate expressions in EBE model...
#> > optimizing duplicate expressions in EBE model...
#> > compiling EBE model...
#> v done
#> rxode2 1.0.0 using 4 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`
#> > Calculating residuals/tables
#> v done
#> > compress origData in nlmixr2 object, save 5952
ranef(fit_nlme)
#>    ID eta.ka eta.cl eta.v
#> 1   1      0      0     0
#> 2   2      0      0     0
#> 3   3      0      0     0
#> 4   4      0      0     0
#> 5   5      0      0     0
#> 6   6      0      0     0
#> 7   7      0      0     0
#> 8   8      0      0     0
#> 9   9      0      0     0
#> 10 10      0      0     0
#> 11 11      0      0     0
#> 12 12      0      0     0
```

<sup>Created on 2022-03-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by billdenney**
Fix #103

The way this works is that it now changes the way that the parameters are sent to `nlmixrNlmeFun()`.  It removes the need for `.nlmixrNlmeUserFun()`, and it directly calls `.nlmixrNlmeFun()`.

In `rxUiGet.nlmeModel()`, is it okay to assume that all parameters are either fixed-effects only or mu-referenced?  Is there a way that a parameter could not be fixed effects only or mu referenced?

### CODE REVIEW

**Comment by mattfidler** [comment]
We can make that requirement, but it needs to have an assertion

**Comment by mattfidler** [comment]
>  Is there a way that a parameter could not be fixed effects only or mu referenced?

The other is a residual parameter, but I think that is covered.

**Comment by mattfidler** [comment]
Note I change the defaults for `nlmeControl`:

- `returnObject = TRUE`
- `msVerbose = TRUE` 

What is your thought about `returnObject=TRUE` instead of the default.

**Comment by billdenney** [comment]
> Note I change the defaults for `nlmeControl`:
> 
> * `returnObject = TRUE`
> * `msVerbose = TRUE`
> 
> What is your thought about `returnObject=TRUE` instead of the default.

I don't like `returnObject=TRUE` instead of the default.  With `returnObject=TRUE`, the user will get back unconverged models; sometimes, that's desired, but it shouldn't be a surprise.

**Comment by mattfidler** [comment]
We can change it back.

**Comment by billdenney** [comment]
I've got a few more changes coming on this one.  I'll also change `returnObject`.

**Comment by mattfidler** [comment]
Great!  I am developing the assertions needed in parallel for rxode2 models

**Comment by mattfidler** [comment]
I think you are assuming the following:

- `rxode2::assertRxUiMixedOnly`
- `rxode2::assertRxUiMuRefOnly`
- `rxode2::assertRxUiNormal`
- `rxode2::assertRxUiSingleEndpoint`

If you call the first on the ui it will be invisibly returned.  You may use this to not have to parse a UI function each call.

**Comment by billdenney** [comment]
I have confirmed that I'm not assuming `rxode2::assertRxUiMuRefOnly`, but I am assuming the others.  But, I don't know where I should put those assertions.

**Comment by mattfidler** [comment]
aThe assertions probably belong between these two lines:

https://github.com/nlmixr2/nlmixr2est/blob/182981cb70977951170af09584597588af3a49d2/R/nlme.R#L525-L526

Then simply:

```r
rxode2::assertRxUiMixedOnly(rx$ui, " for the estimation routine 'nlme', try 'focei'", .var.name="model")
rxode2::assertRxUiNormal(rx$ui, " for the estimation routine 'nlme'", .var.name="model")
rxode2::assertRxUiSingleEndpointl(rx$ui, " for the estimation routine 'nlme'", .var.name="model")
```

The model name should be saved somewhere if it isn't to make it even more explicit.

This also needs `devtools::document()`

**Comment by billdenney** [comment]
I think that this is now complete.

**Comment by mattfidler** [comment]
Thanks @billdenney

**Pull request merged**
