### PR TITLE
Remove unnecessary code

### LINKED ISSUE #266: Does this line of code do anything?
This line doesn't seem to do anything.  Am I missing something or can it be removed?

https://github.com/nlmixr2/nlmixr2est/blob/74dd7236fc6d29f3ff591f82a3ae79667ae98956/R/nlmixr2Est.R#L40

### PR DESCRIPTION
**Pull request by billdenney**
Fix #266

I found a few more that seemed similar.

### CODE REVIEW

**Comment by mattfidler** [comment]
hm. must have been necessary.

**Comment by mattfidler** [comment]
Though logically I agree with you.

**Comment by billdenney** [comment]
The build error has to do with building dependencies and appears unrelated to this code.  I'll try to investigate further this afternoon.

**Comment by billdenney** [comment]
I'm retrying with the CI update to see if the issue was CI or the code itself.  If there is still an error, then we can close this without merging it.

**Comment by billdenney** [comment]
@mattfidler This got a core dump.  Any way to diagnose it?

https://github.com/nlmixr2/nlmixr2est/actions/runs/3342437066/jobs/5534663194#step:7:5120

**Comment by mattfidler** [comment]
Not without reproducing it

**Comment by billdenney** [comment]
I'm giving one last try with the updated CI, and if it doesn't work, I'm going to assume that the code is necessary and document it as such.

**Comment by billdenney** [comment]
I'm not documenting it because it's not totally clear which line(s) are required.  Regardless, enough effort has gone into removing 5 lines of code.

**Comment by mattfidler** [comment]
Sorry @billdenney 

I think I have tried to remove the lines before too and couldn't figure out why they are breaking things too.

**Pull request closed without merging**
