### PR TITLE
Update compilation/linker flags for StanHeaders 2.26 compatibility

### PR DESCRIPTION
**Pull request by andrjohns**

### CODE REVIEW

**Comment by mattfidler** [comment]
This breaks nlmixr2est, as before...

**Comment by mattfidler** [comment]
Never mind the ci may be off.

**Comment by mattfidler** [comment]
Will be fixed by #319 since the stan headers are located elsewhere and do not need to be here any more

**Comment by bgoodri** [comment]
If you don't need to rely on StanHeaders anymore, can you release to CRAN this week? We need to release the StanHeaders that has been years in the making but is still years behind the current Stan development branch.

**Comment by mattfidler** [comment]
Same as rxode2parse

**Pull request closed without merging**
