### PR TITLE
vpcSim works with etas set to 0

### LINKED ISSUE #341: `vpcSim()` requires that etas set to zero must be in the dataset
I set `eta.v ~ 0`, and it fit fine, but `eta.v` is required as a covariate in the dataset for `vpcSim()`:

``` r
library(nlmixr2)
#> Warning: package 'nlmixr2' was built under R version 4.2.3
#> Loading required package: nlmixr2data
#> Warning: package 'nlmixr2data' was built under R version 4.2.3

one.cmt <- function() {
  ini({
    tka <- 0.45
    tcl <- log(c(0, 2.7, 100))
    tv <- 3.45
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

suppressMessages(
  fit <- nlmixr(one.cmt, theo_sd, est="focei", control = list(print = 0))
)
#> calculating covariance matrix
#> done
vpcSim(fit, pred=TRUE)
#> Model:
#> 
#> param(tka,tcl,tv,add.sd,eta.ka,eta.cl,eta.v);
#> ka~exp(tka+eta.ka);
#> cl~exp(tcl+eta.cl);
#> v~exp(tv+eta.v);
#> rx_yj_~2;
#> rx_lambda_~1;
#> rx_low_~0;
#> rx_hi_~1;
#> rx_pred_f_~linCmtA(rx__PTR__,t,0,1,1,cl,v,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,ka,0.0,1.0,0.0,0.0);
#> rx_pred_~rx_pred_f_;
#> rx_r_~(add.sd)^2;
#> ipred=rxTBSi(rx_pred_,rx_lambda_,rx_yj_,rx_low_,rx_hi_);
#> sim=rxTBSi(rx_pred_+sqrt(rx_r_)*err.rxLinCmt,rx_lambda_,rx_yj_,rx_low_,rx_hi_);
#> tad=tad();
#> cmt(rxLinCmt);
#> dvid(1);
#> Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits, : The following parameter(s) are required for solving: eta.v
```

<sup>Created on 2023-04-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by billdenney**
Fix #341

### CODE REVIEW

**Comment by mattfidler** [comment]
This should be fixed in the most recent rxode2.  If not it really needs to
be fixed there.

**Comment by billdenney** [comment]
It makes sense to correct this in the right place.  Should we keep the test that I added or should that move to `rxode2`, too?  (If moved, being refactored for the way that it'd work within `rxode2`.)

**Comment by mattfidler** [comment]
It could be either.  Maybe it is simply that the simulation code doesnt use
the model with the etas in it.  I guess I will have to check.  But in
theory it should use the correct model not adding it to the dataset.  It
would save memory if it is important to the vpc.

**Comment by mattfidler** [comment]
Likely no acces to computer today until late if then

**Comment by mattfidler** [comment]
@billdenney finally had a look,

What about having `$omega` and `$omegaR` reflect the zeros in the estimates.  In theory any other types of simulations from this model that are not tested would work too (not just `vpcSim()`

Still the `$eta` `$phiRSE` etc does not have etas for the zero parameters, which I think is fine.

**Comment by billdenney** [comment]
Having `$omega` reflect the zeros makes sense to me.

**Pull request merged**
